### ISSUE TITLE
make chapters.yaml error

### ISSUE THREAD

**Issue by vinhphunguyen** [islandoftex/arara#144]
Hello,

I have tried to use this make chapters.yaml, from Hughes (https://tex.stackexchange.com/questions/31334/how-to-create-individual-chapter-pdfs-from-included-texs)

```yaml
!config
# Make chapter files rule for arara
# author: Chris Hughes
# last edited by: cmh, May 20th 2013
# http://tex.stackexchange.com/questions/31334/how-to-create-individual-chapter-pdfs
# requires arara 3.0+
#
# Sample usage: Assume you have the following directives in main.tex, with chapter files
#               lions.tex, zebras.tex
#
# % arara: makechapters: {items: [lions]}
# % arara: makechapters: {items: [lions, zebras]}
# % arara: makechapters: {items: [lions, zebras], compileAll: no}
# % arara: makechapters: {items: [lions, zebras], compileAll: yes}
#
# which will create lions.pdf, zebras.pdf
#
# Note that, by default, this compiles main.tex first so that all of the necessary .aux
# files are generated- this is vital for cross referencing to work, particularly in 
# the case of a *forward* cross reference (e.g chapter 2 refers to chapter 3). 
#
# If you set compileAll to false/no/off, then it will *not* compile the main file
# first- be careful with this one, as the necessary .aux files may not be present, and 
# your cross references may break. 
identifier: makechapters
name: MakeChapters
commands: 
- <arara> @{ isTrue( compileAll, engine.concat(' "').concat(file).concat('"') )}
- <arara> @{engine} -jobname=tmpCMH "\includeonly{@{item}}\input{@{file}}" 
- <arara> @{engine} -jobname=tmpCMH "\includeonly{@{item}}\input{@{file}}" 
- <arara> @{ isWindows( "cmd /c move", "mv" ) } tmpCMH.pdf @{item}.pdf
arguments:
- identifier: engine
  flag: <arara> @{parameters.engine}
  default: pdflatex
- identifier: compileAll
  flag: <arara> @{parameters.compileAll}
  default: true
```

------

Arara gave me this:

```
DETAILS ---------------------------------------------------------
com.charleskorn.kaml.IncorrectTypeException at commands[0] on
line 28, column 3: Expected an object, but got a scalar value
```

Could you please help?
